DreamHolidays = ['Nanjing', 'Japan', 'Canada', 'Italy', 'Korea']
print(DreamHolidays)
print(sorted(DreamHolidays))
print(DreamHolidays)
print(sorted(DreamHolidays, reverse=True))
print(DreamHolidays)
DreamHolidays.reverse()
print(DreamHolidays)
DreamHolidays.reverse()
print(DreamHolidays)
DreamHolidays.sort()
print(DreamHolidays)
DreamHolidays.sort(reverse=True)
print(DreamHolidays)